# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: election.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'election.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\x12\x08\x65lection\"\xf1\x01\n\x0f\x45lectionRequest\x12\x10\n\x08regionID\x18\x01 \x01(\x05\x12\x12\n\nregionName\x18\x02 \x01(\t\x12\x15\n\rregionAddress\x18\x03 \x01(\t\x12\x19\n\x11regionPostalCodes\x18\x04 \x01(\t\x12\x14\n\x0c\x66\x65\x64\x65ralState\x18\x05 \x01(\t\x12\x11\n\ttimeStamp\x18\x06 \x01(\t\x12*\n\x0c\x65lectionData\x18\x07 \x03(\x0b\x32\x14.election.PartyVotes\x12\x31\n\x0epreferenceData\x18\x08 \x03(\x0b\x32\x19.election.PreferenceVotes\")\n\nPartyVotes\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05votes\x18\x02 \x01(\x05\".\n\x0fPreferenceVotes\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05votes\x18\x02 \x01(\x05\"%\n\rElectionReply\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2[\n\x0f\x45lectionService\x12H\n\x12SubmitElectionData\x12\x19.election.ElectionRequest\x1a\x17.election.ElectionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=29
  _globals['_ELECTIONREQUEST']._serialized_end=270
  _globals['_PARTYVOTES']._serialized_start=272
  _globals['_PARTYVOTES']._serialized_end=313
  _globals['_PREFERENCEVOTES']._serialized_start=315
  _globals['_PREFERENCEVOTES']._serialized_end=361
  _globals['_ELECTIONREPLY']._serialized_start=363
  _globals['_ELECTIONREPLY']._serialized_end=400
  _globals['_ELECTIONSERVICE']._serialized_start=402
  _globals['_ELECTIONSERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
